# Generated by Django 3.1.7 on 2021-04-14 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('age', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='riskFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('risk_weight', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_diagonised', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagonised', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Past', 'Past')], max_length=200, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('riskfactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.riskfactor')),
            ],
        ),
    ]
