# Generated by Django 3.1.7 on 2021-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210420_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
